---
hibernate:
    #format_sql: true
    cache:
        use_second_level_cache: true
        use_query_cache: true
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
    search:
        default:
            indexBase: '/opt/assessment-tool/lucene'
            indexmanager: near-real-time
            directory_provider: filesystem

dataSource:
    #logSql: true
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    #Staging DB Settings
    url: jdbc:mysql://tatDatabase:3306/tat_db?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
    username: tat_user
    password: tat_pw_11

environments:
    development:
        dataSource:
            properties:
                testOnBorrow: true
                testWhileIdle: true
#           Dev DB Settings
#           A dbCreate value of 'none' allows the database migration plugin to always recreate the database from changelog.groovy
            dbCreate: none
    production:
        dataSource:
            dbCreate: none
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
---
grails:
    profile: web
    codegen:
        defaultPackage: tmf.assessment
#   This enables the database migration plugin to, when the webserver starts, recreate the database from the content
#   in the changelog.groovy file.
    plugin:
        databasemigration:
            updateOnStart: true
            updateOnStartFileName: changelog.groovy
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
        buildDate: '@info.app.buildDate@'

# Keycloak 20
spring:
    security:
        oauth2:
            client:
                registration:
                    keycloak:
                        client-id: tat
                        authorization-grant-type: authorization_code

                provider:
                    keycloak:
                        issuer-uri: http://localhost:8080/realms/trustmark
                        user-name-attribute: preferred_username

            resourceserver:
                jwt:
                    #                 This allows the resource server to validate the access token
                    jwk-set-uri: http://localhost:8080/realms/trustmark/protocol/openid-connect/certs
                    issuer-uri: http://localhost:8080/realms/trustmark

    profiles:
        active: dev
    groovy:
        template:
            check-template-location: false

---
grails:
    gorm:
        failOnError: true
        autoFlush: true
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            jwt:
              - application/jwt
              - text/jwt
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    gsp:
        tldScanPattern: classpath*:/META-INF/*.tld

endpoints:
    jmx:
        unique-names: true
---
quartz:
    autoStartup: true
